{% set name = "argh" %}
{% set version = "0.31.2" %}
{% set hash = "db1c34885804f7d4646c385dc2fb19b45298561322f4c15eae1b133993f9e323" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3
  run:
    - python >=3.8

test:
  imports:
    - argh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neithere/argh
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: The Natural CLI.
  description: |
    An argparse wrapper that doesn't make you say "argh" each time you deal with it.
  doc_url: http://argh.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - daler
    - goanpeca
    - tschoonj
